version: 2.1

orbs:
  win: circleci/windows@5.0

jobs:
  test-linux:
    docker:
      - image: cimg/openjdk:17.0.5

    working_directory: ~/repo

    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    
    steps:
      - checkout
      - run:
          name: test
          command: ./gradlew test

  test-win:
    executor: win/default

    working_directory: ~/repo

    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    
    steps:
      - checkout
      - run:
          name: test
          shell: bash.exe
          command: .\gradlew.bat test

workflows:
   test:
    jobs:
      - test-linux
      - test-win
